version: '3.1'
services:
  stats-server:
    build: ./stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-server
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ./ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - service-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db:5432/ewm-service
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  service-db:
    image: postgres:14-alpine
    container_name: service-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=service
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root